/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import modelo.PerfilesUsuarios;
import modelo.Usuarios;
import persistencia.BD;
import static vista.CatalogoUsuarios.jCBPerfil;

/**
 *
 * @author Luis
 */
public class AgregarPerfilInternal extends javax.swing.JDialog {

    PerfilesUsuarios perfilesUsuarios = new PerfilesUsuarios();
    Usuarios usuarios = new Usuarios();
    
    public AgregarPerfilInternal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtAgregarPerfil = new javax.swing.JTextField();
        jBtnAgregarPerfil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acceso directo Registrar Perfil");
        setResizable(false);

        jBtnAgregarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        jBtnAgregarPerfil.setText("Agregar");
        jBtnAgregarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarPerfilActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del Perfil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtAgregarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAgregarPerfil)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAgregarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAgregarPerfil))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarPerfilActionPerformed
        perfilesUsuarios.setNombre(jTxtAgregarPerfil.getText());
        if(jTxtAgregarPerfil.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Agrega un nombre de Perfil",
                                "Aviso",JOptionPane.WARNING_MESSAGE);
        }else{
            if(perfilesUsuarios.noRepetirMaterial(perfilesUsuarios.getNombre()) == 1){
                JOptionPane.showMessageDialog(rootPane, "Lo sentimos, el Perfil ya existe",
                                "Aviso",JOptionPane.WARNING_MESSAGE);
            }else{
                if(BD.conectarBD()){
                    try {
                        perfilesUsuarios.registrarPerfil();
//                        ope.buscaUsuario();
                        JOptionPane.showMessageDialog(rootPane, "Registro exitoso",
                            "Aviso",JOptionPane.INFORMATION_MESSAGE);
                         usuarios.ListadoComboPerfil(jCBPerfil,"agregar");
                        this.dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, "No se registro el perfil",
                            "Error",JOptionPane.ERROR_MESSAGE);
                        System.out.println("Error al regiatrar un operador perfil: "+e);
                        BD.cerrarConexion();
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Error de conexión",
                            "Error",JOptionPane.ERROR_MESSAGE);
                    BD.cerrarConexion();
                }
            }
        }
    }//GEN-LAST:event_jBtnAgregarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPerfilInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPerfilInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPerfilInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPerfilInternal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarPerfilInternal dialog = new AgregarPerfilInternal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregarPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTxtAgregarPerfil;
    // End of variables declaration//GEN-END:variables
}
