/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import modelo.Pedidos;
import modelo.Personal;
import persistencia.MetodosGlobales;

/**
 *
 * @author Luis
 */
public class AsignarPedidos extends javax.swing.JInternalFrame {

    private static AsignarPedidos asignarPedidos;
    Pedidos pedidos = new Pedidos();
    Personal personal = new Personal();
    
    public static AsignarPedidos getInstancia(){
        if(asignarPedidos == null){
            asignarPedidos = new AsignarPedidos();
        }
        return asignarPedidos;
    }
    
    public AsignarPedidos() {
        initComponents();
        
        MetodosGlobales.LimpiaTabla(jtableAsignarPedidos);
        pedidos.TablaConsultaAsignarPedidos();
        
        personal.llenaComboPersonal(jcbPersonal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtableAsignarPedidos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jcbPersonal = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Asignar Pedidos");

        jtableAsignarPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Folio Pedido", "Estilo", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableAsignarPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableAsignarPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableAsignarPedidos);
        if (jtableAsignarPedidos.getColumnModel().getColumnCount() > 0) {
            jtableAsignarPedidos.getColumnModel().getColumn(0).setMinWidth(80);
            jtableAsignarPedidos.getColumnModel().getColumn(0).setMaxWidth(80);
            jtableAsignarPedidos.getColumnModel().getColumn(2).setMinWidth(150);
            jtableAsignarPedidos.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        jLabel2.setText("Asignar a:");

        jcbPersonal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar16.png"))); // NOI18N
        jButton2.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtableAsignarPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableAsignarPedidosMouseClicked
       int fila = jtableAsignarPedidos.getSelectedRow();
        if(evt.getClickCount()==1){
            personal.setEstilo(jtableAsignarPedidos.getValueAt(fila, 1).toString());
            personal.llenaComboPersonal(jcbPersonal);
       }
    }//GEN-LAST:event_jtableAsignarPedidosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbPersonal;
    public static javax.swing.JTable jtableAsignarPedidos;
    // End of variables declaration//GEN-END:variables
}
