/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import java.awt.Frame;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Clientes;
import modelo.Estilos;
import modelo.Pedidos;
//import modelo.Proveedores;
import persistencia.BD;


/**
 *
 * @author vikto
 */
public class CatalogoPedidos extends javax.swing.JInternalFrame {

    Clientes cli = new Clientes();
    Pedidos ped = new Pedidos();
    Estilos est = new Estilos();
    
     int clics=0;//para habiitar y deshabilitar el teléfono2
     //VARIABLES PARA CAMBIAR LA IMAGEN DEL BOTÓN QUITAR O AGREGAR TELÉFONO 2
     ImageIcon iconoBtnAnadir = new ImageIcon("src/imagenes/anadir.png");     
     ImageIcon iconoBtnQuitar = new ImageIcon("src/imagenes/quitar.png");
     
     public static List<JTextField> txtFieldTallas;

    /**
     * Creates new form CatalogoMateriales
     */
     
     private static CatalogoPedidos catalogoPedidos;
     
     public static CatalogoPedidos getInstancia(){
         if (catalogoPedidos == null) {
             catalogoPedidos = new CatalogoPedidos();
         }
         return catalogoPedidos;
     }
     
    public CatalogoPedidos() {
        txtFieldTallas = new ArrayList<>();
        initComponents();
        est.llenaComboEstilos(jCBEstilos);
        ped.llenaPanelTallas("Nacional");
        jTxtSubTotal.setEditable(false);
        jTxtIva.setEditable(false);
        jTxtTotal.setEditable(false);
//        btnEliminar.setEnabled(false);
//        btnModifyCliente.setEnabled(false);
//        LimpiaTablaClientes();
//        cli.TablaConsultaClientes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        btnAddCliente = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTxtContacto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnModifyCliente = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jCBEstilos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTxtSubTotal = new javax.swing.JTextField();
        jTxtTotal = new javax.swing.JTextField();
        jTxtIva = new javax.swing.JTextField();
        jPanelTallas = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jCBTipoTallas = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Catálogo de Pedidos");
        setAutoscrolls(true);

        jLabel1.setText("Fecha");

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Fecha", "Fecha int", "Fecha cli", "Precio", "Subtotal", "IVA", "Total", "Observaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);
        if (jTableClientes.getColumnModel().getColumnCount() > 0) {
            jTableClientes.getColumnModel().getColumn(0).setMinWidth(50);
            jTableClientes.getColumnModel().getColumn(0).setMaxWidth(5);
            jTableClientes.getColumnModel().getColumn(1).setMinWidth(100);
            jTableClientes.getColumnModel().getColumn(1).setMaxWidth(100);
            jTableClientes.getColumnModel().getColumn(2).setMinWidth(100);
            jTableClientes.getColumnModel().getColumn(2).setMaxWidth(100);
            jTableClientes.getColumnModel().getColumn(3).setMinWidth(100);
            jTableClientes.getColumnModel().getColumn(3).setMaxWidth(100);
            jTableClientes.getColumnModel().getColumn(4).setMinWidth(50);
            jTableClientes.getColumnModel().getColumn(4).setMaxWidth(50);
            jTableClientes.getColumnModel().getColumn(5).setMinWidth(50);
            jTableClientes.getColumnModel().getColumn(5).setMaxWidth(50);
            jTableClientes.getColumnModel().getColumn(6).setMinWidth(50);
            jTableClientes.getColumnModel().getColumn(6).setMaxWidth(50);
            jTableClientes.getColumnModel().getColumn(7).setMinWidth(50);
            jTableClientes.getColumnModel().getColumn(7).setMaxWidth(50);
            jTableClientes.getColumnModel().getColumn(8).setResizable(false);
        }

        btnAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar16.png"))); // NOI18N
        btnAddCliente.setText("Agregar");
        btnAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClienteActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/basura.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar16.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio");

        jTxtContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtContactoActionPerformed(evt);
            }
        });

        jLabel5.setText("Observaciones");

        btnModifyCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/girar.png"))); // NOI18N
        btnModifyCliente.setText("Modificar");
        btnModifyCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyClienteActionPerformed(evt);
            }
        });

        jBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.png"))); // NOI18N
        jBuscar.setText("Búsqueda");
        jBuscar.setFocusable(false);
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jCBEstilos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Estilo");

        jLabel7.setText("Fecha interna");

        jLabel8.setText("Fecha cliente");

        jLabel9.setText("Subtotal");

        jLabel10.setText("IVA");

        jLabel11.setText("Total");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSubTotalActionPerformed(evt);
            }
        });

        jTxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotalActionPerformed(evt);
            }
        });

        jTxtIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIvaActionPerformed(evt);
            }
        });

        jPanelTallas.setBorder(javax.swing.BorderFactory.createTitledBorder("Tallas"));
        jPanelTallas.setLayout(new java.awt.GridLayout(0, 22));

        jLabel12.setText("Estilo");

        jCBTipoTallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Americano", "Frances" }));
        jCBTipoTallas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBTipoTallasItemStateChanged(evt);
            }
        });
        jCBTipoTallas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBTipoTallasMouseClicked(evt);
            }
        });
        jCBTipoTallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoTallasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBTipoTallas, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBEstilos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelTallas, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnAddCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btnModifyCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))
                            .addComponent(jLabel5))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBEstilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTxtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBTipoTallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTallas, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnModifyCliente)
                    .addComponent(btnAddCliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtContactoActionPerformed

    private void btnAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClienteActionPerformed
        // TODO add your handling code here:
//        if (jTxtNombreCliente.getText().equals("") || jTxtDomicilio.getText().equals("")
//                || jTxtContacto.getText().equals("") || jTxtTel.getText().equals("") || jTxtCorreo.equals("")) {
//            JOptionPane.showMessageDialog(rootPane, "Llena todos los campos obligatorios",
//                                "Aviso",JOptionPane.WARNING_MESSAGE);
//        } else {
//                if(BD.conectarBD()){
//                    cli.setNombre(jTxtNombreCliente.getText());
//                    cli.setDomicilio(jTxtDomicilio.getText());
//                    cli.setTelefono(jTxtTel.getText());
//                    cli.setContacto(jTxtContacto.getText());
//                    cli.setCorreo(jTxtCorreo.getText());
//                    try {
//                        cli.RegistraCliente();
//                        JOptionPane.showMessageDialog(rootPane, "Registro exitoso",
//                            "Aviso",JOptionPane.INFORMATION_MESSAGE);
//                        LimpiaCampos();
//                        LimpiaTablaClientes();
//                        cli.TablaConsultaClientes();
//                    } catch (Exception e) {
//                        JOptionPane.showMessageDialog(rootPane, "No se registro el cliente",
//                            "Error",JOptionPane.ERROR_MESSAGE);
////                        System.out.println("Error al registrar un cliente: "+e);
//                        BD.cerrarConexion();
//                    }
//                }else{
//                    JOptionPane.showMessageDialog(rootPane, "Error de conexión",
//                            "Error",JOptionPane.ERROR_MESSAGE);
//                    BD.cerrarConexion();
//                }
//        }
    }//GEN-LAST:event_btnAddClienteActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        // TODO add your handling code here:
//        btnAddCliente.setEnabled(false);
//        btnEliminar.setEnabled(true);
//        btnModifyCliente.setEnabled(true);
//        btnLimpiar.setEnabled(true);
//        
//        if (evt.getClickCount() == 1) {
//            cli.ApuntaCliente();
//            Date date = null;
//            jTxtNombreCliente.setText(cli.getNombre());
//            jTxtDomicilio.setText(cli.getDomicilio());
//            jTxtTel.setText(cli.getTelefono());
//            jTxtContacto.setText(cli.getContacto());
//            jTxtCorreo.setText(cli.getCorreo());
//        }
        
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void btnModifyClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyClienteActionPerformed
        // TODO add your handling code here:
//        if (JOptionPane.showConfirmDialog(rootPane, "Se modificará el cliente, ¿Desea continuar?",
//            "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){ 
//            btnModifyCliente.setEnabled(false);
//            btnEliminar.setEnabled(false);
//            btnAddCliente.setEnabled(true);
//            if (jTxtNombreCliente.getText().equals("") || jTxtDomicilio.getText().equals("")
//                    || jTxtContacto.getText().equals("") || jTxtTel.getText().equals("") || jTxtCorreo.equals("")) {
//                JOptionPane.showMessageDialog(rootPane, "Llena todos los campos obligatorios",
//                                    "Aviso",JOptionPane.WARNING_MESSAGE);
//            } else {
//                if(BD.conectarBD()){
//                    cli.setNombre(jTxtNombreCliente.getText());
//                    cli.setDomicilio(jTxtDomicilio.getText());
//                    cli.setTelefono(jTxtTel.getText());
//                    cli.setContacto(jTxtContacto.getText());
//                    cli.setCorreo(jTxtCorreo.getText());                              
//                    try {
//                        cli.ActualizarCliente(jTableClientes);
//                        JOptionPane.showMessageDialog(rootPane, "Actualización exitosa",
//                            "Aviso",JOptionPane.INFORMATION_MESSAGE);
//                        LimpiaCampos();
//                        LimpiaTablaClientes();
//                        cli.TablaConsultaClientes();
//                    } catch (Exception e) {
//                        JOptionPane.showMessageDialog(rootPane, "No se actualizó el cliente: "+e,
//                            "Error",JOptionPane.ERROR_MESSAGE);
//                        BD.cerrarConexion();
//                    }
//                }else{
//                    JOptionPane.showMessageDialog(rootPane, "Error de conexión",
//                            "Error",JOptionPane.ERROR_MESSAGE);
//                    BD.cerrarConexion();
//                }
//            }
//        }
    }//GEN-LAST:event_btnModifyClienteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        LimpiaCampos();
        btnAddCliente.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnModifyCliente.setEnabled(false);
        clics = 0;//sifnifica que no ha dado un clic
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Se eliminará el cliente, ¿Desea continuar?",
            "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){    
            if(BD.conectarBD()){
                try {
                    cli.EliminaCliente(jTableClientes);
                    JOptionPane.showMessageDialog(rootPane, "El cliente se eliminó con éxito",
                        "Aviso",JOptionPane.INFORMATION_MESSAGE);
                    LimpiaCampos();
                    LimpiaTablaClientes();
                    cli.TablaConsultaClientes();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "No se eliminó el cliente: "+e,
                        "Aviso",JOptionPane.WARNING_MESSAGE);
                    BD.cerrarConexion();
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error de conexión",
                        "Error",JOptionPane.ERROR_MESSAGE);
                BD.cerrarConexion();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
//        BuscadorProveedor miVentanaBuscar = null;
//        
//        miVentanaBuscar = new BuscadorProveedor(miVentanaBuscar,true);
//        miVentanaBuscar.setVisible(true);
//--------COMENTÉ ESTA PARTE PORQUE TUVE QUE ELIMINAR LA CLASE DEL BUSCARPROVEEDOR PARA MEJORARLO Y AHORA SE LLAMA BuscaProveedor----

//        BuscarProveedor buscarProveedor = new BuscarProveedor();
//        Main.jDesktopMain.add(buscarProveedor);
//        buscarProveedor.toFront();
//        buscarProveedor.setVisible(true);
//        Dimension desktopSize = Main.jDesktopMain.getSize();
//        Dimension FrameSize = buscarProveedor.getSize();
//        buscarProveedor.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
//        buscarProveedor.show();//
        Frame frame = JOptionPane.getFrameForComponent(this);
        BuscaCliente buscaCliente = new BuscaCliente(frame,true);
        Dimension desktopSize = Main.jDesktopMain.getSize();
        Dimension FrameSize = buscaCliente.getSize();
        buscaCliente.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        buscaCliente.show();
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jTxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSubTotalActionPerformed

    private void jTxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTotalActionPerformed

    private void jTxtIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIvaActionPerformed

    private void jCBTipoTallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoTallasActionPerformed
        // TODO add your handling code here:
//        System.out.println(this.getTitle());
    }//GEN-LAST:event_jCBTipoTallasActionPerformed

    private void jCBTipoTallasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBTipoTallasMouseClicked
        // TODO add your handling code here:
//        System.out.println(this.getTitle());
    }//GEN-LAST:event_jCBTipoTallasMouseClicked

    private void jCBTipoTallasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBTipoTallasItemStateChanged
        // TODO add your handling code here:
//        System.out.println(evt.getItem().toString());
        jPanelTallas.removeAll();
        jPanelTallas.updateUI();
        ped.llenaPanelTallas(evt.getItem().toString());
    }//GEN-LAST:event_jCBTipoTallasItemStateChanged

    public void LimpiaTablaClientes(){
        try {
            DefaultTableModel modelo = (DefaultTableModel)jTableClientes.getModel();
            int filas = jTableClientes.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
            System.out.println("Limpieza exitosa!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al intentar limpiar la tabla Clientes: "+e,
                    "Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void LimpiaCampos(){
//        jTxtNombreCliente.setText(null);
//        jTxtDomicilio.setText(null);
//        jTxtTel.setText(null);
//        jTxtContacto.setText(null);
//        jTxtCorreo.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCliente;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModifyCliente;
    private javax.swing.JButton jBuscar;
    private javax.swing.JComboBox<String> jCBEstilos;
    private javax.swing.JComboBox<String> jCBTipoTallas;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanelTallas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTableClientes;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTxtContacto;
    public static javax.swing.JTextField jTxtIva;
    public static javax.swing.JTextField jTxtSubTotal;
    public static javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
