/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import java.awt.Frame;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.Clientes;
import modelo.Estilos;
import modelo.Pedidos;
//import modelo.Proveedores;
import persistencia.BD;
import persistencia.MetodosGlobales;


/**
 *
 * @author vikto
 */
public class CatalogoPedidos extends javax.swing.JInternalFrame {

    Clientes cli = new Clientes();
    Pedidos ped = new Pedidos();
    Estilos est = new Estilos();
    MetodosGlobales metodosGlobales = new MetodosGlobales();
    
     int clics=0;//para habiitar y deshabilitar el teléfono2
     //VARIABLES PARA CAMBIAR LA IMAGEN DEL BOTÓN QUITAR O AGREGAR TELÉFONO 2
     ImageIcon iconoBtnAnadir = new ImageIcon("src/imagenes/anadir.png");     
     ImageIcon iconoBtnQuitar = new ImageIcon("src/imagenes/quitar.png");
     
     public static List<JTextField> txtFieldTallas;

    /**
     * Creates new form CatalogoMateriales
     */
     
     private static CatalogoPedidos catalogoPedidos;
     
     public static CatalogoPedidos getInstancia(){
         if (catalogoPedidos == null) {
             catalogoPedidos = new CatalogoPedidos();
         }
         return catalogoPedidos;
     }
     
    public CatalogoPedidos() {
        txtFieldTallas = new ArrayList<>();
        initComponents();
        cli.llenaComboClientes(jCBClientes);
        est.llenaComboEstilos(jCBEstilos);
        ped.llenaPanelTallas("Nacional");
        jTxtSubTotal.setEditable(false);
        jTxtIva.setEditable(false);
        jTxtTotal.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddCliente = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTxtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnModifyCliente = new javax.swing.JButton();
        jDCFecha1 = new com.toedter.calendar.JDateChooser();
        jCBEstilos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jDCFechaInterna = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDCFechaCliente = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTxtSubTotal = new javax.swing.JTextField();
        jTxtTotal = new javax.swing.JTextField();
        jTxtIva = new javax.swing.JTextField();
        jPanelTallas = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jCBTipoTallas = new javax.swing.JComboBox<>();
        jBtnCalcTotales = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jCBClientes = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Catálogo de Pedidos");
        setAutoscrolls(true);

        jLabel1.setText("Fecha");

        btnAddCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar16.png"))); // NOI18N
        btnAddCliente.setText("Agregar");
        btnAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClienteActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/basura.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar16.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio");

        jTxtPrecio.setForeground(java.awt.Color.blue);
        jTxtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPrecioActionPerformed(evt);
            }
        });

        jLabel5.setText("Observaciones");

        btnModifyCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/girar.png"))); // NOI18N
        btnModifyCliente.setText("Modificar");
        btnModifyCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyClienteActionPerformed(evt);
            }
        });

        jCBEstilos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Estilo");

        jLabel7.setText("Fecha interna");

        jLabel8.setText("Fecha cliente");

        jLabel9.setText("Subtotal");

        jLabel10.setText("IVA");

        jLabel11.setText("Total");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTxtSubTotal.setForeground(java.awt.Color.blue);
        jTxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSubTotalActionPerformed(evt);
            }
        });

        jTxtTotal.setForeground(java.awt.Color.blue);
        jTxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotalActionPerformed(evt);
            }
        });

        jTxtIva.setForeground(java.awt.Color.blue);
        jTxtIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIvaActionPerformed(evt);
            }
        });

        jPanelTallas.setBorder(javax.swing.BorderFactory.createTitledBorder("Tallas"));
        jPanelTallas.setLayout(new java.awt.GridLayout(0, 22));

        jLabel12.setText("Tipo de talla");

        jCBTipoTallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Americano", "Frances" }));
        jCBTipoTallas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBTipoTallasItemStateChanged(evt);
            }
        });
        jCBTipoTallas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBTipoTallasMouseClicked(evt);
            }
        });
        jCBTipoTallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoTallasActionPerformed(evt);
            }
        });

        jBtnCalcTotales.setText("Calcular totales");
        jBtnCalcTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcTotalesActionPerformed(evt);
            }
        });

        jLabel13.setText("Cliente");

        jCBClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDCFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBEstilos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDCFechaInterna, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDCFechaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBTipoTallas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(571, 571, 571))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(228, 228, 228)
                                        .addComponent(btnAddCliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnModifyCliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLimpiar))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnCalcTotales))
                            .addComponent(jPanelTallas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBEstilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jDCFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jDCFechaInterna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDCFechaCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBTipoTallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel11)
                        .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jTxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanelTallas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCalcTotales))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnLimpiar)
                            .addComponent(btnModifyCliente)
                            .addComponent(btnAddCliente))))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPrecioActionPerformed

    private void jTxtTallasKeyReleased(java.awt.event.KeyEvent evt) { 
        int code = evt.getKeyCode(); 
        char caracter = evt.getKeyChar(); 
        System.out.println("Code: "+code+" caracter: "+caracter);
    } 
    
    private void btnAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClienteActionPerformed
        // TODO add your handling code here:
        String estilo = (String) jCBEstilos.getSelectedItem();
        Date date1 = jDCFecha1.getDate();
        Date dateInterna = jDCFechaInterna.getDate();
        Date dateCliente = jDCFechaCliente.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//        if (metodosGlobales.validaFecha(jDCFecha1)==null || estilo.equals("-- Seleccione --") || jTxtPrecio.getText().equals("")
//                || jTxtSubTotal.getText().equals("") || jTxtIva.getText().equals("") || jTxtTotal.equals("")) {
//            JOptionPane.showMessageDialog(rootPane, "Llena todos los campos obligatorios",
//                                "Aviso",JOptionPane.WARNING_MESSAGE);
//        } 
        for (int i = 0; i < txtFieldTallas.size(); i++) {
            if(!txtFieldTallas.get(i).getText().equals("")){
                System.out.println("item JTextField de tallas: "+txtFieldTallas.get(i).getName());
            }
        }
//          else {
//                if(BD.conectarBD()){
//                    cli.setNombre(jTxtNombreCliente.getText());
//                    cli.setDomicilio(jTxtDomicilio.getText());
//                    cli.setTelefono(jTxtTel.getText());
//                    cli.setContacto(jTxtContacto.getText());
//                    cli.setCorreo(jTxtCorreo.getText());
//                    try {
//                        cli.RegistraCliente();
//                        JOptionPane.showMessageDialog(rootPane, "Registro exitoso",
//                            "Aviso",JOptionPane.INFORMATION_MESSAGE);
//                        LimpiaCampos();
//                        LimpiaTablaClientes();
//                        cli.TablaConsultaClientes();
//                    } catch (Exception e) {
//                        JOptionPane.showMessageDialog(rootPane, "No se registro el cliente",
//                            "Error",JOptionPane.ERROR_MESSAGE);
////                        System.out.println("Error al registrar un cliente: "+e);
//                        BD.cerrarConexion();
//                    }
//                }else{
//                    JOptionPane.showMessageDialog(rootPane, "Error de conexión",
//                            "Error",JOptionPane.ERROR_MESSAGE);
//                    BD.cerrarConexion();
//                }
//        }
    }//GEN-LAST:event_btnAddClienteActionPerformed

    private void btnModifyClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyClienteActionPerformed
        // TODO add your handling code here:
//        if (JOptionPane.showConfirmDialog(rootPane, "Se modificará el cliente, ¿Desea continuar?",
//            "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){ 
//            btnModifyCliente.setEnabled(false);
//            btnEliminar.setEnabled(false);
//            btnAddCliente.setEnabled(true);
//            if (jTxtNombreCliente.getText().equals("") || jTxtDomicilio.getText().equals("")
//                    || jTxtContacto.getText().equals("") || jTxtTel.getText().equals("") || jTxtCorreo.equals("")) {
//                JOptionPane.showMessageDialog(rootPane, "Llena todos los campos obligatorios",
//                                    "Aviso",JOptionPane.WARNING_MESSAGE);
//            } else {
//                if(BD.conectarBD()){
//                    cli.setNombre(jTxtNombreCliente.getText());
//                    cli.setDomicilio(jTxtDomicilio.getText());
//                    cli.setTelefono(jTxtTel.getText());
//                    cli.setContacto(jTxtContacto.getText());
//                    cli.setCorreo(jTxtCorreo.getText());                              
//                    try {
//                        cli.ActualizarCliente(jTableClientes);
//                        JOptionPane.showMessageDialog(rootPane, "Actualización exitosa",
//                            "Aviso",JOptionPane.INFORMATION_MESSAGE);
//                        LimpiaCampos();
//                        LimpiaTablaClientes();
//                        cli.TablaConsultaClientes();
//                    } catch (Exception e) {
//                        JOptionPane.showMessageDialog(rootPane, "No se actualizó el cliente: "+e,
//                            "Error",JOptionPane.ERROR_MESSAGE);
//                        BD.cerrarConexion();
//                    }
//                }else{
//                    JOptionPane.showMessageDialog(rootPane, "Error de conexión",
//                            "Error",JOptionPane.ERROR_MESSAGE);
//                    BD.cerrarConexion();
//                }
//            }
//        }
    }//GEN-LAST:event_btnModifyClienteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        LimpiaCampos();
        btnAddCliente.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnModifyCliente.setEnabled(false);
        clics = 0;//sifnifica que no ha dado un clic
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
//        if (JOptionPane.showConfirmDialog(rootPane, "Se eliminará el cliente, ¿Desea continuar?",
//            "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){    
//            if(BD.conectarBD()){
//                try {
//                    cli.EliminaCliente(jTableClientes);
//                    JOptionPane.showMessageDialog(rootPane, "El cliente se eliminó con éxito",
//                        "Aviso",JOptionPane.INFORMATION_MESSAGE);
//                    LimpiaCampos();
//                    LimpiaTablaClientes();
//                    cli.TablaConsultaClientes();
//                } catch (Exception e) {
//                    JOptionPane.showMessageDialog(rootPane, "No se eliminó el cliente: "+e,
//                        "Aviso",JOptionPane.WARNING_MESSAGE);
//                    BD.cerrarConexion();
//                }
//            }else{
//                JOptionPane.showMessageDialog(rootPane, "Error de conexión",
//                        "Error",JOptionPane.ERROR_MESSAGE);
//                BD.cerrarConexion();
//            }
//        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSubTotalActionPerformed

    private void jTxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTotalActionPerformed

    private void jTxtIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtIvaActionPerformed

    private void jCBTipoTallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoTallasActionPerformed
        // TODO add your handling code here:
//        System.out.println(this.getTitle());
    }//GEN-LAST:event_jCBTipoTallasActionPerformed

    private void jCBTipoTallasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBTipoTallasMouseClicked
        // TODO add your handling code here:
//        System.out.println(this.getTitle());
    }//GEN-LAST:event_jCBTipoTallasMouseClicked

    private void jCBTipoTallasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBTipoTallasItemStateChanged
        // TODO add your handling code here:
//        System.out.println(evt.getItem().toString());
        jPanelTallas.removeAll();
        jPanelTallas.updateUI();
        ped.llenaPanelTallas(evt.getItem().toString());
    }//GEN-LAST:event_jCBTipoTallasItemStateChanged

    private void jBtnCalcTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcTotalesActionPerformed
        // TODO add your handling code here:
        int totalCantTallas = 0;
        double precio = !jTxtPrecio.getText().equals("") ? Double.parseDouble(jTxtPrecio.getText()) : 0;
        for (int i = 0; i < txtFieldTallas.size()-1; i++) {
            if(!txtFieldTallas.get(i).getText().equals("")){
                totalCantTallas += Integer.parseInt(txtFieldTallas.get(i).getText());
            }
        }
        txtFieldTallas.get(txtFieldTallas.size()-1).setText(""+totalCantTallas);
        if(!jTxtPrecio.getText().equals("")){
            double subTotal = precio * totalCantTallas;
            jTxtSubTotal.setText("$"+subTotal);
            double iva = subTotal * 0.16;
            jTxtIva.setText("$"+iva);
            double total = subTotal + iva;
            jTxtTotal.setText("$"+total);
        }
    }//GEN-LAST:event_jBtnCalcTotalesActionPerformed

    public void LimpiaTablaClientes(){
//        try {
//            DefaultTableModel modelo = (DefaultTableModel)jTableClientes.getModel();
//            int filas = jTableClientes.getRowCount();
//            for (int i = 0; filas > i; i++) {
//                modelo.removeRow(0);
//            }
//            System.out.println("Limpieza exitosa!");
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Error al intentar limpiar la tabla Clientes: "+e,
//                    "Error",JOptionPane.ERROR_MESSAGE);
//        }
    }
    
    public static void LimpiaCampos(){
//        jTxtNombreCliente.setText(null);
//        jTxtDomicilio.setText(null);
//        jTxtTel.setText(null);
//        jTxtContacto.setText(null);
//        jTxtCorreo.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCliente;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModifyCliente;
    private javax.swing.JButton jBtnCalcTotales;
    private javax.swing.JComboBox<String> jCBClientes;
    private javax.swing.JComboBox<String> jCBEstilos;
    private javax.swing.JComboBox<String> jCBTipoTallas;
    private com.toedter.calendar.JDateChooser jDCFecha1;
    private com.toedter.calendar.JDateChooser jDCFechaCliente;
    private com.toedter.calendar.JDateChooser jDCFechaInterna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanelTallas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTxtIva;
    public static javax.swing.JTextField jTxtPrecio;
    public static javax.swing.JTextField jTxtSubTotal;
    public static javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
