/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Materiales;
import persistencia.BD;
import persistencia.IconCellRenderer;
import persistencia.MetodosGlobales;

/**
 *
 * @author vikto
 */
public class CatalogoMateriales extends javax.swing.JInternalFrame {

    Materiales materiales = new Materiales();
    
    //OBJETITO PARA HACER UNA INSTANCIA
    private static CatalogoMateriales catalogoMateriales;
    
    
    //ImageIcon icon1 = new ImageIcon(getClass().getResource("/imagenes/anadir.png"));
    
    public static CatalogoMateriales getInstancia(){
        if(catalogoMateriales == null){
            catalogoMateriales = new CatalogoMateriales();
        }
            return catalogoMateriales;
    }
    
    public CatalogoMateriales() {
        initComponents();
        
        jbtnEliminarMaterial.setEnabled(false);
        jbtnModificarMaterial.setEnabled(false);
        
        MetodosGlobales.LimpiaTabla(jTableMateriales);
        materiales.TablaConsultaMateriales();
        
        
//        DefaultTableModel modelo = (DefaultTableModel)jTableProveedoresMaterial.getModel();
//        jTableProveedoresMaterial.setDefaultRenderer(Object.class, new IconCellRenderer());
//        Object[] fila = new Object[2];
//        for (int i = 0; i < 10; i++) {
//        modelo.setValueAt(fila[0] = new JLabel(icon1), i, 0);
//        modelo.setValueAt("Contenido", i, 1);
//        modelo.setValueAt("Contenido", i, 2);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtNombreMaterial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMateriales = new javax.swing.JTable();
        jbtnAgregarMaterial = new javax.swing.JButton();
        jbtnEliminarMaterial = new javax.swing.JButton();
        jbtnLimpiarMaterial = new javax.swing.JButton();
        jbtnModificarMaterial = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCBUnidad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTxtRendimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtDescripciónBM = new javax.swing.JTextField();
        jbtnAgregarProveedorMaterial = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProveedoresMaterial = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jBtnBuscarMaterial = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTxtPrecio = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Catálogo de Materiales");
        setAutoscrolls(true);

        jLabel1.setText("Nombre:");

        jTableMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre de Material", "Unidad", "Rendimiento", "Descripción BM", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMaterialesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMateriales);
        if (jTableMateriales.getColumnModel().getColumnCount() > 0) {
            jTableMateriales.getColumnModel().getColumn(0).setMinWidth(10);
        }

        jbtnAgregarMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar16.png"))); // NOI18N
        jbtnAgregarMaterial.setText("Agregar");
        jbtnAgregarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarMaterialActionPerformed(evt);
            }
        });

        jbtnEliminarMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/basura.png"))); // NOI18N
        jbtnEliminarMaterial.setText("Eliminar");
        jbtnEliminarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarMaterialActionPerformed(evt);
            }
        });

        jbtnLimpiarMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar16.png"))); // NOI18N
        jbtnLimpiarMaterial.setText("Limpiar");
        jbtnLimpiarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarMaterialActionPerformed(evt);
            }
        });

        jbtnModificarMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/girar.png"))); // NOI18N
        jbtnModificarMaterial.setText("Modificar");
        jbtnModificarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarMaterialActionPerformed(evt);
            }
        });

        jLabel3.setText("Unidad");

        jCBUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Unidad", "LAM", "Pza", "Lat", "Por", "Lt", "Rol", "Mil", "M2" }));

        jLabel4.setText("Rendimiento");

        jTxtRendimiento.setToolTipText("");

        jLabel5.setText("Descripción BM");

        jbtnAgregarProveedorMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        jbtnAgregarProveedorMaterial.setText("Seleccionar Proveedores");
        jbtnAgregarProveedorMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarProveedorMaterialActionPerformed(evt);
            }
        });

        jTableProveedoresMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Proveedor", "Tipo Proveedor", "Descripción Proveedor", "Editar", "Eliminar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableProveedoresMaterial);

        jLabel7.setText("Proveedores");

        jBtnBuscarMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.png"))); // NOI18N
        jBtnBuscarMaterial.setText("Busqueda");
        jBtnBuscarMaterial.setFocusable(false);
        jBtnBuscarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarMaterialActionPerformed(evt);
            }
        });

        jLabel2.setText("Materiales");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N

        jLabel6.setText("Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 145, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jbtnAgregarMaterial)
                .addGap(47, 47, 47)
                .addComponent(jbtnModificarMaterial)
                .addGap(49, 49, 49)
                .addComponent(jbtnEliminarMaterial)
                .addGap(65, 65, 65)
                .addComponent(jbtnLimpiarMaterial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnBuscarMaterial))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(263, 780, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNombreMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtRendimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtDescripciónBM, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jbtnAgregarProveedorMaterial)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jBtnBuscarMaterial)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtNombreMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jCBUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtRendimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxtDescripciónBM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAgregarProveedorMaterial))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAgregarMaterial)
                    .addComponent(jbtnEliminarMaterial)
                    .addComponent(jbtnLimpiarMaterial)
                    .addComponent(jbtnModificarMaterial))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAgregarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarMaterialActionPerformed
        
        if (jTxtNombreMaterial.getText().equals("") || jCBUnidad.getSelectedIndex()==0
                || jTxtRendimiento.getText().equals("") || jTxtPrecio.getText().equals("") 
                || jTxtDescripciónBM.getText().equals("")) {//VALIDA QUE NO HAYA CAMPOS VACÍOS
            JOptionPane.showMessageDialog(rootPane, "Llena todos los campos obligatorios",
                                "Aviso",JOptionPane.WARNING_MESSAGE);
        } else {
            if(materiales.noRepetirMaterial(jTxtNombreMaterial.getText().trim())==1){//VALIDA SI EL MATERIAL YA SE ENCUENTRA REGISTRADO EN LA BD
                JOptionPane.showMessageDialog(rootPane, "Lo sentimos. Este material ya existe",
                                "Aviso",JOptionPane.WARNING_MESSAGE); 
            }else{
                if(jTableProveedoresMaterial.getRowCount() <=0){//VALIDA QUE NO ESTE LA TABLA DE PROVEEDORES VACÍA
                    JOptionPane.showMessageDialog(rootPane, "Ingresa al menos un Proveedor para registrar el Material",
                                "Aviso",JOptionPane.WARNING_MESSAGE);
                }else{
                    if(BD.conectarBD()){
                        materiales.setNombre(jTxtNombreMaterial.getText());
                        materiales.setUnidad(jCBUnidad.getSelectedItem().toString());
                        materiales.setRendimiento(jTxtRendimiento.getText());
                        materiales.setPrecio(Double.parseDouble(jTxtPrecio.getText()));
                        materiales.setDescripcionBM(jTxtDescripciónBM.getText());

                        try {
                            materiales.registrarMaterial();
    //                        ope.buscaUsuario();
                            JOptionPane.showMessageDialog(rootPane, "Registro exitoso",
                                "Aviso",JOptionPane.INFORMATION_MESSAGE);
                            LimpiaCampos();
                            MetodosGlobales.LimpiaTabla(jTableMateriales);
                            materiales.TablaConsultaMateriales();
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(rootPane, "No se registro el operador",
                                "Error",JOptionPane.ERROR_MESSAGE);
                            System.out.println("Error al regiatrar un operador: "+e);
                            BD.cerrarConexion();
                        }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Error de conexión",
                                "Error",JOptionPane.ERROR_MESSAGE);
                        BD.cerrarConexion();
                    }
                }
            }
            
        }
    }//GEN-LAST:event_jbtnAgregarMaterialActionPerformed

    private void jbtnAgregarProveedorMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarProveedorMaterialActionPerformed
        Frame frame = JOptionPane.getFrameForComponent(this);
        AgregarProveedorMaterial agregarProveedor = new AgregarProveedorMaterial(frame,true);
        Dimension desktopSize = Main.jDesktopMain.getSize();
        Dimension FrameSize = agregarProveedor.getSize();
        agregarProveedor.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        agregarProveedor.show();
    }//GEN-LAST:event_jbtnAgregarProveedorMaterialActionPerformed

    private void jTableMaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMaterialesMouseClicked
        jbtnAgregarMaterial.setEnabled(false);
        jbtnEliminarMaterial.setEnabled(true);
        jbtnModificarMaterial.setEnabled(true);
        jbtnLimpiarMaterial.setEnabled(true);
        
        if (evt.getClickCount() == 1) {
            materiales.ApuntaMaterial();
            jTxtNombreMaterial.setText(materiales.getNombre());
            jCBUnidad.setSelectedItem(materiales.getUnidad());
            jTxtRendimiento.setText(materiales.getRendimiento());
            jTxtPrecio.setText(Double.toString(materiales.getPrecio()));
            jTxtDescripciónBM.setText(materiales.getDescripcionBM());
            //FIN DE LA VALIDACIÓN TELÉFONO 2
        }
    }//GEN-LAST:event_jTableMaterialesMouseClicked

    private void jbtnModificarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarMaterialActionPerformed
         if (JOptionPane.showConfirmDialog(rootPane, "Se modificará el material, ¿Desea continuar?",
            "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){ 
            jbtnModificarMaterial.setEnabled(false);
            jbtnEliminarMaterial.setEnabled(false);
            jbtnAgregarMaterial.setEnabled(true);
            if (jTxtNombreMaterial.getText().equals("") || jCBUnidad.getSelectedIndex()==0
                    || jTxtRendimiento.getText().equals("") || jTxtPrecio.getText().equals("") 
                    || jTxtDescripciónBM.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Llena todos los campos obligatorios",
                                    "Aviso",JOptionPane.WARNING_MESSAGE);
            } else {
                if(BD.conectarBD()){
                    materiales.setNombre(jTxtNombreMaterial.getText());
                    materiales.setUnidad(jCBUnidad.getSelectedItem().toString());
                    materiales.setRendimiento(jTxtRendimiento.getText());
                    materiales.setPrecio(Double.parseDouble(jTxtPrecio.getText()));
                    materiales.setDescripcionBM(jTxtDescripciónBM.getText());                            
                    try {
                        materiales.ActualizarProveedor(jTableMateriales);
                        JOptionPane.showMessageDialog(rootPane, "Actualización exitosa",
                            "Aviso",JOptionPane.INFORMATION_MESSAGE);
                        LimpiaCampos();
                        MetodosGlobales.LimpiaTabla(jTableMateriales);
                        materiales.TablaConsultaMateriales();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, "No se actualizó el material: "+e,
                            "Error",JOptionPane.ERROR_MESSAGE);
                        BD.cerrarConexion();
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Error de conexión",
                            "Error",JOptionPane.ERROR_MESSAGE);
                    BD.cerrarConexion();
                }
            }
        }
    }//GEN-LAST:event_jbtnModificarMaterialActionPerformed

    private void jbtnEliminarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarMaterialActionPerformed
         if (JOptionPane.showConfirmDialog(rootPane, "Se eliminará el material, ¿Desea continuar?",
            "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
             jbtnModificarMaterial.setEnabled(false);
            jbtnEliminarMaterial.setEnabled(false);
            jbtnAgregarMaterial.setEnabled(true);
            if(BD.conectarBD()){
                try {
                    materiales.EliminaMaterial(jTableMateriales);
                    JOptionPane.showMessageDialog(rootPane, "El material se eliminó con éxito",
                        "Aviso",JOptionPane.INFORMATION_MESSAGE);
                    LimpiaCampos();
                    MetodosGlobales.LimpiaTabla(jTableMateriales);
                    materiales.TablaConsultaMateriales();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "No se eliminó el material: "+e,
                        "Aviso",JOptionPane.WARNING_MESSAGE);
                    BD.cerrarConexion();
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error de conexión",
                        "Error",JOptionPane.ERROR_MESSAGE);
                BD.cerrarConexion();
            }
        }
    }//GEN-LAST:event_jbtnEliminarMaterialActionPerformed

    private void jbtnLimpiarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarMaterialActionPerformed
        LimpiaCampos();
        jbtnAgregarMaterial.setEnabled(true);
        jbtnEliminarMaterial.setEnabled(false);
        jbtnModificarMaterial.setEnabled(false);
        
    }//GEN-LAST:event_jbtnLimpiarMaterialActionPerformed

    private void jBtnBuscarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarMaterialActionPerformed
        Frame frame = JOptionPane.getFrameForComponent(this);
        BuscaMaterial buscaMaterial = new BuscaMaterial(frame,true);
        Dimension desktopSize = Main.jDesktopMain.getSize();
        Dimension FrameSize = buscaMaterial.getSize();
        buscaMaterial.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        buscaMaterial.show();
    }//GEN-LAST:event_jBtnBuscarMaterialActionPerformed


     public static void LimpiaCampos(){
        jTxtNombreMaterial.setText(null);
        jCBUnidad.setSelectedIndex(0);
        jTxtRendimiento.setText(null);
        jTxtPrecio.setText(null);
        jTxtDescripciónBM.setText(null);
    }
        
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarMaterial;
    private javax.swing.JButton jButton1;
    public static javax.swing.JComboBox<String> jCBUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTableMateriales;
    public static javax.swing.JTable jTableProveedoresMaterial;
    public static javax.swing.JTextField jTxtDescripciónBM;
    public static javax.swing.JTextField jTxtNombreMaterial;
    public static javax.swing.JTextField jTxtPrecio;
    public static javax.swing.JTextField jTxtRendimiento;
    private javax.swing.JButton jbtnAgregarMaterial;
    private javax.swing.JButton jbtnAgregarProveedorMaterial;
    private javax.swing.JButton jbtnEliminarMaterial;
    private javax.swing.JButton jbtnLimpiarMaterial;
    private javax.swing.JButton jbtnModificarMaterial;
    // End of variables declaration//GEN-END:variables
}
