/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import modelo.ReporPagoPorDestajo;
import persistencia.MetodosGlobales;

/**
 *
 * @author Luis
 */
public class DetallesPagoPorDestajo extends javax.swing.JDialog {

    ReporPagoPorDestajo reporPagoDesta = new ReporPagoPorDestajo();
    
    public DetallesPagoPorDestajo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        //PARA CENTRAR LOS DATOS Y ENCABEZADO DEL JTABLE
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        //Centra el contenido del jTable
        tcr.setHorizontalAlignment(SwingConstants.CENTER);
        jTableDetallePagoDestajo.getColumnModel().getColumn(0).setCellRenderer(tcr);
        jTableDetallePagoDestajo.getColumnModel().getColumn(1).setCellRenderer(tcr);
        jTableDetallePagoDestajo.getColumnModel().getColumn(2).setCellRenderer(tcr);
        //Centra el encabezado del jTable
        tcr =  ( DefaultTableCellRenderer ) 
        jTableDetallePagoDestajo.getTableHeader().getDefaultRenderer (); 
        tcr. setHorizontalAlignment ( JLabel.CENTER );
        
        int fila = PagosPorDestajo.jTablePrincipalPagosDestajo.getSelectedRow();
        reporPagoDesta.setIdPedido((int)PagosPorDestajo.jTablePrincipalPagosDestajo.getValueAt(fila, 0));//MANDA EL ID DEL PEDIDO
        
        MetodosGlobales.LimpiaTabla(jTableDetallePagoDestajo);
        reporPagoDesta.consultarPorProceso();
        
        jlblNomtrabajador.setText(reporPagoDesta.getNombreTrabajador());//LLAMA EL NOMBRE DEL TRABAJADOR/PERSONAL
        jlblNomEstilo.setText(reporPagoDesta.getNomEstilo());
        jlblNomProceso.setText(reporPagoDesta.getProceso());
        jlblTotalPares.setText(PagosPorDestajo.jTablePrincipalPagosDestajo.getValueAt(fila, 2).toString());
        jlblTipoTalla.setText(reporPagoDesta.getTipoTalla());
        jlblDestajo.setText("$ "+Double.toString(reporPagoDesta.getDestajo()));
        jlblTotalPagar.setText(PagosPorDestajo.jTablePrincipalPagosDestajo.getValueAt(fila, 3).toString());
        

        
       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDetallePagoDestajo = new javax.swing.JTable();
        jlblNomtrabajador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlblTotalPagar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblTipoTalla = new javax.swing.JLabel();
        jbtnOK = new javax.swing.JButton();
        jlblEstilo = new javax.swing.JLabel();
        jlblNomEstilo = new javax.swing.JLabel();
        jlblNomProceso = new javax.swing.JLabel();
        jlblTotalPares = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlblDestajo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalle Pago por Destajo");

        jTableDetallePagoDestajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Talla", "Cantidad", "Semana"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDetallePagoDestajo);
        if (jTableDetallePagoDestajo.getColumnModel().getColumnCount() > 0) {
            jTableDetallePagoDestajo.getColumnModel().getColumn(0).setMinWidth(60);
            jTableDetallePagoDestajo.getColumnModel().getColumn(0).setMaxWidth(60);
            jTableDetallePagoDestajo.getColumnModel().getColumn(2).setMinWidth(60);
            jTableDetallePagoDestajo.getColumnModel().getColumn(2).setMaxWidth(60);
        }

        jlblNomtrabajador.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jlblNomtrabajador.setText("Nombre del trabajador");
        jlblNomtrabajador.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Proceso:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Total a pagar");

        jlblTotalPagar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotalPagar.setForeground(new java.awt.Color(255, 102, 0));
        jlblTotalPagar.setText("$");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Total de pares:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Tipo de talla:");

        jlblTipoTalla.setText("Muestra tipo");

        jbtnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ok.png"))); // NOI18N
        jbtnOK.setText("Ok");
        jbtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOKActionPerformed(evt);
            }
        });

        jlblEstilo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jlblEstilo.setText("Estilo:");

        jlblNomEstilo.setText("Nombre del estilo");

        jlblNomProceso.setText("Nombre proceso");

        jlblTotalPares.setText("Muestra total pares");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pecio destajo:");

        jlblDestajo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblDestajo.setText("Muestra precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblNomProceso))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblEstilo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblNomEstilo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblTotalPares))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblTipoTalla))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblDestajo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblNomtrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jlblTotalPagar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jlblNomtrabajador)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblEstilo)
                            .addComponent(jlblNomEstilo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblNomProceso)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jlblTotalPares))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jlblTipoTalla))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jlblDestajo))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlblTotalPagar))
                .addGap(22, 22, 22)
                .addComponent(jbtnOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesPagoPorDestajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesPagoPorDestajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesPagoPorDestajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesPagoPorDestajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetallesPagoPorDestajo dialog = new DetallesPagoPorDestajo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableDetallePagoDestajo;
    private javax.swing.JButton jbtnOK;
    private javax.swing.JLabel jlblDestajo;
    private javax.swing.JLabel jlblEstilo;
    private javax.swing.JLabel jlblNomEstilo;
    private javax.swing.JLabel jlblNomProceso;
    private javax.swing.JLabel jlblNomtrabajador;
    private javax.swing.JLabel jlblTipoTalla;
    private javax.swing.JLabel jlblTotalPagar;
    private javax.swing.JLabel jlblTotalPares;
    // End of variables declaration//GEN-END:variables
}
