/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import modelo.LoginModel;
import persistencia.BD;

/**
 *
 * @author Luis
 */
public class LoginInternal extends javax.swing.JInternalFrame {

    LoginModel login = new LoginModel();
    //Main main = new Main();
    
    private static LoginInternal loginInternal;
    public static LoginInternal getInstancia(){
        if(loginInternal == null){
            loginInternal = new LoginInternal();
        }
        return loginInternal;
    }
    
    public LoginInternal() {
        initComponents();
        
//        jbtnIniciar.addKeyListener(new java.awt.event.KeyAdapter() {
//            public void keyPressed(java.awt.event.KeyEvent e){
//                JOptionPane.showMessageDialog(rootPane, "Presionaste enter " + login.getNomUsuario(),
//                        "Aviso",JOptionPane.INFORMATION_MESSAGE);
//            }
//        });
            this.getRootPane().setDefaultButton(jbtnIniciar);
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtContrasena = new javax.swing.JPasswordField();
        jbtnCancelar = new javax.swing.JButton();
        jbtnIniciar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Inicio de Sesión");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/quitar16px.png"))); // NOI18N
        jbtnCancelar.setText("Cancelar");

        jbtnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iniciar-la-sesion.png"))); // NOI18N
        jbtnIniciar.setText("Iniciar");
        jbtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnIniciar)
                        .addGap(60, 60, 60)
                        .addComponent(jbtnCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(38, 38, 38)
                            .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jTxtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnIniciar)
                    .addComponent(jbtnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIniciarActionPerformed
        if (jTxtUsuario.getText().equals("") || jTxtContrasena.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingresa los campos necesarios",
                "Aviso",JOptionPane.INFORMATION_MESSAGE);
        } else {
            if(BD.conectarBD()){
                login.setUsuario(jTxtUsuario.getText());
                login.setContrasena(jTxtContrasena.getText());

                if(login.iniciarSesion()== true){
                    JOptionPane.showMessageDialog(rootPane, "Bienvenido " + login.getNomUsuario(),
                        "Aviso",JOptionPane.INFORMATION_MESSAGE);
                    Main.menuNomUsuario.setText(login.getNomUsuario());
                    this.dispose();
                    //main.setVisible(true);
                    Main.menuCatalogos.setVisible(true);
                    Main.subMenuUsuarios.setVisible(true);
                    Main.subMenuCerrarSesion.setVisible(true);

                }else{
                    JOptionPane.showMessageDialog(rootPane, "Usuario o contraseña incorrecto",
                        "Error de conexión",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        //esto es prueba
    }//GEN-LAST:event_jbtnIniciarActionPerformed

    public void limpiarCampos(){
        jTxtUsuario.setText("");
        jTxtContrasena.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JPasswordField jTxtContrasena;
    public static javax.swing.JTextField jTxtUsuario;
    private javax.swing.JButton jbtnCancelar;
    public static javax.swing.JButton jbtnIniciar;
    // End of variables declaration//GEN-END:variables
}
