/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import modelo.Materiales;
import modelo.Proveedores;
import persistencia.BD;
import persistencia.MetodosGlobales;

/**
 *
 * @author alber
 */
public class ModificarProveedorMaterial extends javax.swing.JDialog {

    Proveedores proveedores = new Proveedores();
    Materiales materiales = new Materiales();
    
    
    public ModificarProveedorMaterial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        proveedores.leerDatosLista(jListProveedores);
         int fila = CatalogoMateriales.jTableProveedoresMaterial.getSelectedRow();
        jListProveedores.setSelectedValue(CatalogoMateriales.jTableProveedoresMaterial.getValueAt(fila, 2), true);
        if(CatalogoMateriales.jTableProveedoresMaterial.getValueAt(fila, 3).equals("Primario")){
            jRBPrimario.setSelected(true);
        }else{
            jRBSecundario.setSelected(true);
        }
        jTxtDescripcion.setText((String) CatalogoMateriales.jTableProveedoresMaterial.getValueAt(fila, 4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSelecPrioridad = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProveedores = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jTxtDescripcion = new javax.swing.JTextField();
        jRBPrimario = new javax.swing.JRadioButton();
        jRBSecundario = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar descripción del Material por Proveedor");
        setResizable(false);

        jLabel2.setText("Proveedores");

        jListProveedores.setToolTipText("");
        jScrollPane1.setViewportView(jListProveedores);

        jLabel1.setText("Descripción del Materaal por el proveedor");

        buttonGroupSelecPrioridad.add(jRBPrimario);
        jRBPrimario.setText("Primario");

        buttonGroupSelecPrioridad.add(jRBSecundario);
        jRBSecundario.setText("Secundario");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/girar.png"))); // NOI18N
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel1))
                                    .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jRBPrimario)
                                .addGap(37, 37, 37)
                                .addComponent(jRBSecundario))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRBPrimario)
                            .addComponent(jRBSecundario))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nomProveedor = "";
        int id=0;
        String tipo = "";
        int validaPrimario = 0;
        String rbPrimario = "";
        int filaMaterialProveedor = CatalogoMateriales.jTableProveedoresMaterial.getSelectedRow();
        int filaMateriales = CatalogoMateriales.jTableMateriales.getSelectedRow();

        if(jListProveedores.getSelectedIndex() >=0){
            if(!jTxtDescripcion.getText().equals("")){
                if(jRBPrimario.isSelected() || jRBSecundario.isSelected()){

                    nomProveedor = jListProveedores.getSelectedValue();
                    proveedores.optenerIdProveedor(nomProveedor);
                    id= proveedores.getIdProveedor();

                    if(jRBPrimario.isSelected()){
                        tipo = "Primario";
                        rbPrimario = "Primario";
                    }
                    if(jRBSecundario.isSelected()){
                        tipo = "Secundario";
                    }
                    materiales.setTipoProveedor(tipo);
                    materiales.setDescripcionProveedor(jTxtDescripcion.getText());
                    materiales.setNombreProveedor(jListProveedores.getSelectedValue());
                        
                    int filas =CatalogoMateriales.jTableProveedoresMaterial.getRowCount();
                    for(int i=0; i<filas; i++){
                        if(CatalogoMateriales.jTableProveedoresMaterial.getValueAt(i, 3).equals(rbPrimario) ){
                            validaPrimario = 1;
                        }
                    }
                            if(CatalogoMateriales.jTableProveedoresMaterial.getValueAt(filaMaterialProveedor, 0).equals("")){//VALIDA SI ES EDITADO SIN BD
                                CatalogoMateriales.jTableProveedoresMaterial.setValueAt(id,filaMaterialProveedor, 1);
                                CatalogoMateriales.jTableProveedoresMaterial.setValueAt(materiales.getNombreProveedor(),filaMaterialProveedor, 2);
                                CatalogoMateriales.jTableProveedoresMaterial.setValueAt(materiales.getDescripcionProveedor(),filaMaterialProveedor, 4);
                            if(validaPrimario==1){
                                JOptionPane.showMessageDialog(rootPane, "Ya existe un proveedor primario. \n Solamente los demas datos se actualizarán",
                                    "Aviso",JOptionPane.WARNING_MESSAGE);
                            }else{
                                CatalogoMateriales.jTableProveedoresMaterial.setValueAt(materiales.getTipoProveedor(),filaMaterialProveedor, 3);
                               
                            }
                            }else{//SI LA EDICIÓN ES CON BD EN SEGUIDA DE ESTA ELSE SE EJECUTA
                                 try {
                                    if(validaPrimario==1){
                                        JOptionPane.showMessageDialog(rootPane, "Ya existe un proveedor primario. \n Solamente los demas datos se actualizarán",
                                    "Aviso",JOptionPane.WARNING_MESSAGE);
                                        materiales.setTipoProveedor((String) CatalogoMateriales.jTableProveedoresMaterial.getValueAt(filaMaterialProveedor, 3));
                                        materiales.ActualizarMaterialProveedor(CatalogoMateriales.jTableProveedoresMaterial,id);
                                    }else{
                                        materiales.ActualizarMaterialProveedor(CatalogoMateriales.jTableProveedoresMaterial,id);
                                        
                                     }
                                    JOptionPane.showMessageDialog(rootPane, "Actualización exitosa",
                                        "Aviso",JOptionPane.INFORMATION_MESSAGE);
                                        MetodosGlobales.LimpiaTabla(CatalogoMateriales.jTableProveedoresMaterial);
                                        materiales.TablaConsultaProveedoresMateriales((int) CatalogoMateriales.jTableMateriales.getValueAt(filaMateriales, 0));
                                        this.dispose();
                                    
                                    
                                } catch (Exception e) {
                                    JOptionPane.showMessageDialog(rootPane, "No se registro el operador",
                                        "Error",JOptionPane.ERROR_MESSAGE);
                                    System.out.println("Error al regiatrar un operador: "+e);
                                    BD.cerrarConexion();
                                }
                            }

                }else{
                    JOptionPane.showMessageDialog(rootPane, "Seleccion si el Proveedor es Primario o Secundario",
                        "Aviso",JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Imposible registrar. Descripción Vacía",
                    "Aviso",JOptionPane.WARNING_MESSAGE);
            }

        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccion un Proveedor de la lista",
                "Aviso",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProveedorMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProveedorMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProveedorMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProveedorMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarProveedorMaterial dialog = new ModificarProveedorMaterial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSelecPrioridad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JList<String> jListProveedores;
    private javax.swing.JRadioButton jRBPrimario;
    private javax.swing.JRadioButton jRBSecundario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtDescripcion;
    // End of variables declaration//GEN-END:variables
}
