/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.ReporPagoPorDestajo;
import persistencia.MetodosGlobales;

/**
 *
 * @author Luis
 */
public class PagosPorDestajo extends javax.swing.JDialog {

    ReporPagoPorDestajo reporPagoDesta = new ReporPagoPorDestajo();
    
    public PagosPorDestajo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenaComboNumSemanas(jcbNumSemana);        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtNombreTrabajador = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrincipalPagosDestajo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jcbNumSemana = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pagos por Destajo");

        jLabel1.setText("Nombre del Tabajador");

        jtxtNombreTrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNombreTrabajadorKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTablePrincipalPagosDestajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Folio", "Estilo", "Total Pares", "Destajo $"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePrincipalPagosDestajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePrincipalPagosDestajoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePrincipalPagosDestajo);

        jLabel2.setText("# Semana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbNumSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jtxtNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jcbNumSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePrincipalPagosDestajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePrincipalPagosDestajoMouseClicked
       if(evt.getClickCount() ==2){
           
        Frame frame = JOptionPane.getFrameForComponent(this);
        DetallesPagoPorDestajo detallePagoDesta = new DetallesPagoPorDestajo(frame,true);
        Dimension desktopSize = Main.jDesktopMain.getSize();
        Dimension FrameSize = detallePagoDesta.getSize();
        detallePagoDesta.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        detallePagoDesta.show();
       }
    }//GEN-LAST:event_jTablePrincipalPagosDestajoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reporPagoDesta.setNombreTrabajador(jtxtNombreTrabajador.getText());
        reporPagoDesta.setNumSemana(Integer.parseInt(jcbNumSemana.getSelectedItem().toString()));
        
        MetodosGlobales.LimpiaTabla(jTablePrincipalPagosDestajo);
        reporPagoDesta.buscarEstilosPorPersonal();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtNombreTrabajadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreTrabajadorKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            reporPagoDesta.setNombreTrabajador(jtxtNombreTrabajador.getText());
            reporPagoDesta.setNumSemana(Integer.parseInt(jcbNumSemana.getSelectedItem().toString()));
            
            MetodosGlobales.LimpiaTabla(jTablePrincipalPagosDestajo);
            reporPagoDesta.buscarEstilosPorPersonal();
        }
    }//GEN-LAST:event_jtxtNombreTrabajadorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagosPorDestajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagosPorDestajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagosPorDestajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagosPorDestajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PagosPorDestajo dialog = new PagosPorDestajo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
     public void llenaComboNumSemanas(JComboBox combo){
        DefaultComboBoxModel comboSemanaNum = new DefaultComboBoxModel();
        try {
            
            for(int i =0; i<48; i++){
                comboSemanaNum.addElement(i+1);
                combo.setModel(comboSemanaNum);
            }
//            BD.conectarBD();
//            String sql = "select * from clientes";
//            rs = BD.ejecutarSQLSelect(sql);
//            rsm = rs.getMetaData();
//            combo.setModel(comboCliente);
//            comboCliente.addElement("-- Seleccione --");
//            while (rs.next()) {
//                this.idCliente = Integer.parseInt(rs.getString("idCliente"));
//                this.nombre = rs.getString("nombre");
//                comboCliente.addElement(rs.getObject("nombre"));
//                combo.setModel(comboCliente);
//            }
//            BD.cerrarConexion();
        } catch (Exception e) {
            System.out.println("Excepción: "+e);
            JOptionPane.showMessageDialog(null, "Error al mostrar el listado del número de semanas",
                    "Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTablePrincipalPagosDestajo;
    private javax.swing.JComboBox<String> jcbNumSemana;
    private javax.swing.JTextField jtxtNombreTrabajador;
    // End of variables declaration//GEN-END:variables
}
